module.exports = {
  ROLE: ['attendee', 'event_manager'],

  // http-Status-Codes
  STATUS_SUCCESS: 200,
  STATUS_CREATED: 201,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_NOT_FOUND: 404,
  STATUS_INTERNAL_SERVER_ERROR: 500,
  STATUS_TOKEN_EXPIRED: 419,
  STATUS_STATUS_CONFLICT: 409,
};
